{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "acrloader.fullname" . }}
  labels:
    {{- include "acrloader.labels" . | nindent 4 }}
data:
  ACR_BEARER_TOKEN: {{ .Values.acr.bearerToken | b64enc | quote }}
  {{- if .Values.oc.enabled }}
  OC_PASS: {{ .Values.oc.pass | b64enc | quote }}
  {{- end }}
  {{- if .Values.minio.enabled }}
  MINIO_ACCESS_KEY: {{ .Values.minio.access_key | b64enc | quote }}
  MINIO_SECRET_KEY: {{ .Values.minio.secret_key | b64enc | quote }}
  {{- end }}
{{- end }}
