{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "acrloader.fullname" . }}
  labels:
    {{- include "acrloader.labels" . | nindent 4 }}
data:
  ACR_BEARER_TOKEN: {{ .Values.acr.bearerToken | b64enc | quote }}
  OC_PASS: {{ .Values.oc.pass | b64enc | quote }}
{{- end }}
