name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  pull_request:

jobs:
  python-poetry:
    uses: radiorabe/actions/.github/workflows/release-python-poetry.yaml@v0.11.1
    secrets:
      RABE_PYPI_TOKEN: ${{ secrets.RABE_PYPI_TOKEN }}
  release-container:
    uses: radiorabe/actions/.github/workflows/release-container.yaml@v0.11.1
    needs:
      - python-poetry
    with:
      image: 'ghcr.io/radiorabe/acrloader'
      name: 'acrloader'
      display-name: 'RaBe ACR Loader'
      tags: 'minimal rhel9 rabe s2i python python311 acr owncloud'
  helm-chart:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    needs:
      - release-container
    permissions:
      actions: none
      checks: none
      contents: none
      deployments: none
      issues: none
      packages: write
      pull-requests: none
      repository-projects: none
      security-events: none
      statuses: none
      id-token: none
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare Chart Metadata
        id: meta
        run: echo version=${GITHUB_REF#refs/tags/v} >> $GITHUB_OUTPUT

      - name: Set up Helm
        uses: azure/setup-helm@v3.5
        with:
          version: v3.12.0

      - name: Package Chart
        run: helm package --version ${{ steps.meta.outputs.version }} --app-version ${{ steps.meta.outputs.version }} --destination=dist charts/acrloader

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Chart
        run: helm push dist/*.tgz oci://ghcr.io/radiorabe/helm
