name: Test

on:
  pull_request:

jobs:
  pre-commit:
    uses: radiorabe/actions/.github/workflows/test-pre-commit.yaml@3f1ee42ffa54794a512d3989c34e3b4514de64cc # v0.43.1
  python-poetry:
    uses: radiorabe/actions/.github/workflows/test-python-poetry.yaml@3f1ee42ffa54794a512d3989c34e3b4514de64cc # v0.43.1
    with:
      version: '3.12'
  helm-chart:
    name: Test Helm Chart
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Build dev image
        run: |
          docker build -t ghcr.io/radiorabe/acrloader:latest -f Dockerfile .
          docker save -o /tmp/acrloader.tar ghcr.io/radiorabe/acrloader:latest

      - name: Set up Helm
        uses: azure/setup-helm@dda3372f752e03dde6b3237bc9431cdc2f7a02a2 # v5.0.0
        with:
          version: v3.12.0

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.x'

      - name: Install chart-testing
        uses: helm/chart-testing-action@6ec842c01de15ebb84c8627d2744a0c2f2755c9f # v2.8.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct --config=.github/ct.yaml list-changed)
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Run chart-testing (lint)
        run: ct --config=.github/ct.yaml lint

      - name: Create kind cluster
        uses: helm/kind-action@ef37e7f390d99f746eb8b610417061a60e82a6cc # v1.14.0

      - name: Load dev image
        run: |
          kind load image-archive /tmp/acrloader.tar --name chart-testing

      - name: Run chart-testing (install)
        run: ct --config=.github/ct.yaml install
